### ISSUE TITLE
iOS: Since v3.0 (WKWebview) cookies are not persisted anymore

### ISSUE THREAD

**Issue by scthi** [trigger-corp/trigger.io-tabs#24]
**Problem**
Users have to re-authenticate when using an app within the tabs module. 
The affected customer is using **SessionCookies**.  **Since v3.0** of the tabs module the cookies are gone after closing the tab. On Android the cookies are preserved. So we have an inconsistency between Android and iOS since v3.

**Steps to Reproduce**
1. Open this [page](https://req-playground.scthi.tech/cookies) in tab module. It sets/updates a cookie on every visit and prints out the previous value of that cookie.
2. Use it as target of the tabs module.
3. After closing & reopening the tab the cookie value is gone.

**Possible solution**
Use [WKProcessPool](https://developer.apple.com/documentation/webkit/wkprocesspool) to share cookies between WKWebview instances.

```Objective-c
if (processPool == nil) {
    processPool = [[WKProcessPool alloc] init];
}

WKWebViewConfiguration *config = [[WKWebViewConfiguration alloc] init];
config.processPool = processPool;
webview = [[WKWebView alloc] initWithFrame:frame configuration:config];
```

See: https://stackoverflow.com/questions/25797972/cookie-sharing-between-multiple-wkwebviews

**Comment by scthi** [comment]
I try to obtain the cookie data from the response to store it, but it doesn't work.  🤷🏻‍♂️

https://github.com/trigger-corp/trigger.io-tabs/pull/25

![Uploading Screenshot 2019-12-20 at 17.12.59.png…]()

**Comment by scthi** [comment]
False alert -> closing this.

The tab behaves correctly, since the particular page uses session cookies (no expire date).
I'm not sure why it worked in v2.x version of the tabs module, my guess would be due the memory leak / incorrect cleanup logic.

**Comment by scthi** [comment]
@antoinevg Although from a technical web standards view the tab module behaves correctly, I re-opened this issue for two reasons:
1. From a user/client POV the session (of the cookie) should bound to the life-time of the app not the tab
2. There is currently an inconsistency between Android and iOS

**Comment by antoinevg** [comment]
Fixed in 517f20354cb8c0581263af5c819fbde5b85350c6 

Published as:
```
"tabs": {
    "version": "3.6",
    "config": { }
},
```

Needs: 
```
"platform_version": "v2.8.5"
```

Thank you! :-)

**Comment by scthi** [comment]
@antoinevg Thanks for looking into this. 

I tried it, but makes my app freeze immediately after opening a tab. 
iPhone 8, iOS: 13.3

Currently I have not time to look further into this. Please let me know if you have troubles reproducing the issue.

**Comment by antoinevg** [comment]
Hrmmm… It's working for me with:
```
forge.tabs.open("https://req-playground.scthi.tech/cookies", function () {});
```

There were some corresponding changes made to the underlying platform to support this, are you on platform `v2.8.5` ?

I'm on an iPhone XR, iOS 13.3.

**Comment by scthi** [comment]
Yes, I built the app with the new platform. Mby one of the other modules we are using is not compatible. I will check again...

**Comment by scthi** [comment]
@antoinevg My tests with our app are still the same. So I checked out the v3.6.1 tag of the tabs module and tested in the forge inspector.

There I see a similar behaviour like you describe here: https://github.com/trigger-corp/trigger.io-tabs/pull/27#issuecomment-575637795

With **opaqueTopBar: true** the content is behind the header and the statusbar is transparent.
And the "close" button doesn't work anymore...

**Comment by scthi** [comment]
@antoinevg I built our app with **"platform_version": "v2.8.5"** and **"tabs": 3.6.2** (opaqueTopBar: true).

The good news:
* header & statusbar look good now
* close button works
* cookies work

The bad news:
* content is still behind header
* reload via botton navigationbar doesn't work

<details>
<img src="https://user-images.githubusercontent.com/318533/72626831-af9f3b00-394b-11ea-924a-f41a7aaa1ff3.png"/>
</details>

**Comment by antoinevg** [comment]
1. **Content is still behind header:** Looks like iOS treats the navigationBar as transparent when no tint is set and moves content underneath.
2. **Reload via bottom navigationbar doesn't work:** Whoops :-)

Fixed in: de68616c88fc4ced2e4103ca9b56e7a0ebf528ef

Published as:
```
"tabs": {
    "version": "3.6.3",
    "config": { }
},
```

Needs:
```
"platform_version": "v2.8.5"
```

Thank you for taking the time to iterate through all the tabs issues with me today!

**Comment by scthi** [comment]
> Thank you for taking the time to iterate through all the tabs issues with me today!
My pleasure. Thank _you_ for being so responsive. 👏

The reload btn works now. ✅
But the layout is still broken. We do have a tint color set, opaqueTopBar: true. ❌

**Comment by scthi** [comment]
I also have this when checking out **v.3.6.3** of the tabs module and running the ForgeInspector with

```
forge.tabs.openAdvanced({
        url: "https://req-playground.scthi.now.sh/cookies",
        opaqueTopBar: true,
        navigationToolbar: true,
    }
```

<details>
<img src="https://user-images.githubusercontent.com/318533/72630310-5be42000-3952-11ea-8812-3037a919e1fb.png"/>
</details>

**Comment by antoinevg** [comment]
Okay, managed to replicate it.

Have to call it a day for now, will wrap this up on Monday!

**Comment by scthi** [comment]
Have a nice weekend

**Comment by antoinevg** [comment]
I took another stab at it and finally managed to get it working as a Custom Class in interface builder - *touch wood* that seems to have done the job.

That was a good suggestion thank you!

Fixed in: 76f42247bf5efcf2127b8f578b2633b044b9f0a2

Published as:
```
"tabs": {
    "version": "3.6.4",
    "config": { }
},
```

Needs:
```
"platform_version": "v2.8.5"
```

**Comment by scthi** [comment]
Sweet... looks good to me. We will do further testing. Thanks a lot.

**Comment by ice8lue** [comment]
@antoinevg With the `platform_version` increase, this tabs update depends on a currently staging level platform, which feels problematic. As we'd like to roll this tabs update out with our next release, is there anything blocking the platform release right now?

**Comment by scthi** [comment]
@antoinevg Do you think it's feasible to get the tabs module changes backwards compatible with platform_version v2.8.4? That would solve us a lot of headaches.

**Comment by antoinevg** [comment]
> scthi commented on Dec 20, 2019
> **Possible solution**
> Use WKProcessPool to share cookies between WKWebview instances.

These changes are in v2.8.5 and cannot be back ported to v2.8.4 without breaking older versions of the tabs module.

**Comment by scthi** [comment]
@antoinevg So the _only_ reason is the passed in parent `WKWebView` to get the `WKProcessPool`? Because in that case, I think it should also work by having the `WKProcessPool` lazy initialized as static variable in the tabs module itself, or?

**Comment by antoinevg** [comment]
`WKProcessPool` needs to belong to ForgeCore's `WKWebView` if you want it to persist across multiple tabs.

This also required changes to life-cycle and init orders of both ForgeCore and tabs module which is why it would break earlier versions of the tabs module.

Please believe me when I tell you I don't say this carelessly:

> These changes are in v2.8.5 and cannot be back ported to v2.8.4 without breaking older versions of the tabs module.

**Comment by scthi** [comment]
@antoinevg I've no doubt that you're right 😀. Thanks for the explanation.
